data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings ="?", stringsAsFactors = FALSE)
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
datarange <- subset(data, Date == as.Date("2007-02-01") | Date == as.Date("2007-02-02"))
datarange <- within(datarange, { timestamp=format(as.POSIXct(paste(Date, Time)), "%Y-%m-%d %H:%M:%S") })
datarange$timestamp <- strptime(datarange$timestamp, "%Y-%m-%d %H:%M:%S")
png(filename="plot2.png")
plot(x=datarange$timestamp, y=datarange$Global_active_power, type="n", xlab="", ylab="Global Active Power (kilowatts)")
lines(x=datarange$timestamp, y=datarange$Global_active_power)
dev.off()